// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itjeccdndvdxmpmfzjee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0amVjY2RuZHZkeG1wbWZ6amVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODc0NjUsImV4cCI6MjA2NTM2MzQ2NX0.OobIaYPbWkJ5xWDJYpy2Bzkq5Q99XhtwErFNESRE4xM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);